"""empty message

Revision ID: 34cdd26db74b
Revises: 
Create Date: 2020-08-14 13:53:24.729919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cdd26db74b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('config_json', sa.String(length=1000), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('subdomains', sa.Integer(), nullable=False),
    sa.Column('subdomains_alive', sa.Integer(), nullable=False),
    sa.Column('scan_start', sa.Integer(), nullable=False),
    sa.Column('scan_complete', sa.Integer(), nullable=False),
    sa.Column('ips', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('summary_string', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dir_scans',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=True),
    sa.Column('scan_init', sa.Integer(), nullable=True),
    sa.Column('scan_end', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nuclei',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('scanner', sa.String(length=50), nullable=True),
    sa.Column('scan_init', sa.Integer(), nullable=True),
    sa.Column('scan_end', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nuclei')
    op.drop_table('dir_scans')
    op.drop_table('project')
    op.drop_table('config')
    # ### end Alembic commands ###
